version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "4050:3306"
    environment:
      MYSQL_ROOT_PASSWORD: iboioroot
      MYSQL_USER: iboio
      MYSQL_PASSWORD: 1234
    volumes:
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d
      - ./storage/mysql:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3050:3050"
    depends_on:
      - mysql